### ISSUE TITLE
bug ajout photo

### ISSUE THREAD

**Issue by Redunka** [VincentChalnot/ComTSo#25]
pas moyen d'ajouter des photo dans un nouvel album (pas essayé pour un vieux non plus) 
http://comtso.fr/forum/albums/290/add_photos
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please e-mail us at [email] and let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by gigilenain** [comment]
Pareil pour moi seulement une photo est passée aujourd'hui !
