### ISSUE TITLE
Images uploadées visibles pour tous les utilisateurs

### ISSUE THREAD

**Issue by Dotpeach** [VincentChalnot/ComTSo#29]
Un comportement étrange sur le système d'upload de photos.

En partant d'un topic > Clic sur l'icône **manage photos** > Clic sur **Ajouter des photos**
On arrive sur le système d'upload d'images sur lequel apparaît les images des autres utilisateurs.

En revanche, une fois que l'on uploade une image sur cette même page, un filtre s'applique et seules mes propres images sont visibles.

**Comment by VincentChalnot** [comment]
Fixed in a past commit
